groups:
- name: LocustStressAlerts
  rules:
  
  # Redis Alerts
  - alert: RedisHighMemoryUsage
    expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.85
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High Redis Memory Usage"
      description: "Redis memory usage has exceeded 85% of the maximum allowed memory."

  - alert: RedisHighCPUUsage
    expr: avg(rate(redis_cpu_user_seconds_total[1m])) > 0.85
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High Redis CPU Usage"
      description: "Redis CPU usage has exceeded 85% for more than a minute."

  - alert: RedisHighCommandLatency
    expr: rate(redis_command_duration_seconds_sum[1m]) / rate(redis_command_duration_seconds_count[1m]) > 0.02
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High Redis Command Latency"
      description: "The average Redis command latency has exceeded 20ms."

  - alert: RedisOpsPerSecDrop
    expr: rate(redis_commands_processed_total[1m]) < 500
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Redis Operations per Second Drop"
      description: "Redis operations per second have dropped below 500."

  - alert: RedisHighCacheMissRatio
    expr: rate(redis_keyspace_misses_total[1m]) / (rate(redis_keyspace_hits_total[1m]) + rate(redis_keyspace_misses_total[1m])) > 0.10
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High Redis Cache Miss Ratio"
      description: "Redis cache miss ratio has exceeded 10%."

  # PostgreSQL Alerts
  - alert: PostgresHighConnectionCount
    expr: pg_stat_activity_count{datname="<your_database_name>"} > 100
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High PostgreSQL Connection Count"
      description: "The number of active connections to PostgreSQL has exceeded 100."

  - alert: PostgresHighCPUUsage
    expr: avg(rate(node_cpu_seconds_total{job="postgres"}[1m])) > 0.85
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High PostgreSQL CPU Usage"
      description: "PostgreSQL CPU usage has exceeded 85% for more than a minute."

  - alert: PostgresSlowQueries
    expr: rate(pg_stat_activity_duration_seconds_sum[1m]) / rate(pg_stat_activity_duration_seconds_count[1m]) > 0.5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Slow PostgreSQL Queries"
      description: "The average query execution time has exceeded 500ms."

  - alert: PostgresHighLockWaitTime
    expr: avg(rate(pg_locks_waiting[1m])) > 10
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High PostgreSQL Lock Wait Time"
      description: "The number of waiting locks in PostgreSQL has exceeded 10."

  - alert: PostgresHighTransactionRollbacks
    expr: rate(pg_stat_database_xact_rollback[1m]) > 10
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High PostgreSQL Transaction Rollbacks"
      description: "The number of transaction rollbacks in PostgreSQL has exceeded 10 per minute."
