global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
      - to: '<email address>'
        from: '<email address>'
        smarthost: 'smtp.gmail.com:587'
        auth_username: '<emailaddress>'
        auth_password: '<password>'