global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - api_url: 'https://api.telegram.org'
    bot_token: '<BOT_TOKEN>'
    chat_id: <CHAT_ID>
    message: '{{ template "telegram.default.message" . }}'

templates:
- '/etc/alertmanager/template/*.tmpl'
